version = "0.1.0"
content_dir = "pages"

[pdf.spine]
title = "Rheo Menual"
vertebrae = [
  "frontmatter.typ",
  "index.typ",
  "why-is-rheo.typ",
  "getting-started.typ",
  "relative-linking.typ",
  "rheotoml.typ",
  "build-dir.typ",
  "content-dir.typ",
  "formats.typ",
  "spines.typ",
  "custom-css.typ",
  "endmatter.typ",
]
merge = true

[epub.spine]
title = "Rheo Manual"
vertebrae = [
  "index.typ",
  "why-is-rheo.typ",
  "getting-started.typ",
  "relative-linking.typ",
  "rheotoml.typ",
  "build-dir.typ",
  "content-dir.typ",
  "formats.typ",
  "spines.typ",
  "custom-css.typ",
  "endmatter.typ",
]
